spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/georouting
    username: abitesh      
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080